#!/bin/sh -e

XORGCONFPATH="/usr/share/X11/xorg.conf.d/"

cd ${XORGCONFPATH}
if [ "$(grep "Panda" /proc/cpuinfo)" != "" ]; then
    echo "Panda detected"
    ln -sf 99-pvr.conf.panda 99-pvr.conf
else
    echo "Blaze detected"
    ln -sf 99-pvr.conf.blaze 99-pvr.conf
fi
cd - > /dev/null

exit 0
